package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/dark-agents/research-mcp/internal/mem"
	"github.com/mark3labs/mcp-go/mcp"
)

// ---------------------------------------------------------------------------
// Memory export + diff. Two new tools that complement the existing recall
// and list endpoints: one turns a research run into a sharable document,
// the other shows what changed between two runs.
// ---------------------------------------------------------------------------

type exportRunArgs struct {
	RunID  int64  `json:"run_id" jsonschema:"Run id from dark_mem_list_runs or dark_research_* tool output"`
	Format string `json:"format,omitempty" jsonschema:"Output format: 'markdown' (default) or 'json'"`
}

func exportRunTool() Tool {
	def := mcp.NewTool("dark_mem_export_run",
		mcp.WithDescription("Export a research run as a shareable document. Format 'markdown' (default) returns a readable report with title, query, backend used, and items grouped by source. Format 'json' returns the full run + items as a JSON object. Use to hand off findings to humans, archive investigations, or feed downstream pipelines."),
		mcp.WithNumber("run_id", mcp.Required(), mcp.Description("Run id")),
		mcp.WithString("format", mcp.Description("Output format: 'markdown' (default) | 'json'")),
	)
	return Tool{
		Definition: def,
		Handler: func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			var args exportRunArgs
			if err := bindArgs(req, &args); err != nil {
				return nil, err
			}
			if args.Format == "" {
				args.Format = "markdown"
			}
			m := sharedMem()
			if m == nil {
				return nil, fmt.Errorf("mem store not configured")
			}
			// Load the run + items via Recall (substring empty returns nothing)
			// → instead, query items by run_id via ListResearchItems.
			runs, err := m.ListResearchRuns(ctx, "", 9999)
			if err != nil {
				return nil, err
			}
			var run *mem.ResearchRun
			for i := range runs {
				if runs[i].ID == args.RunID {
					run = &runs[i]
					break
				}
			}
			if run == nil {
				return jsonResult(map[string]any{"found": false, "reason": "run not found"}), nil
			}
			items, err := m.ListResearchItems(ctx, args.RunID, "", 9999)
			if err != nil {
				return nil, err
			}

			switch args.Format {
			case "json":
				return jsonResult(map[string]any{
					"run":   run,
					"items": items,
				}), nil
			case "markdown", "md":
				md := renderRunMarkdown(run, items)
				return jsonResult(map[string]any{
					"run_id":   args.RunID,
					"format":   "markdown",
					"markdown": md,
				}), nil
			default:
				return nil, fmt.Errorf("unsupported format %q (use 'markdown' or 'json')", args.Format)
			}
		},
	}
}

// renderRunMarkdown turns a run + its items into a Markdown report.
// Items are grouped by source and sorted by confidence desc.
func renderRunMarkdown(run *mem.ResearchRun, items []mem.Item) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Research run #%d\n\n", run.ID)
	fmt.Fprintf(&b, "**Query:** `%s`  \n", run.Query)
	fmt.Fprintf(&b, "**Intent:** `%s`  \n", run.Intent)
	if run.BackendUsed != "" {
		fmt.Fprintf(&b, "**Backend:** `%s`  \n", run.BackendUsed)
	}
	fmt.Fprintf(&b, "**Took:** %d ms  \n", run.TookMs)
	fmt.Fprintf(&b, "**Avg confidence:** %.2f  \n", run.ConfidenceAvg)
	fmt.Fprintf(&b, "**Items:** %d  \n", len(items))
	if run.SessionID != "" {
		fmt.Fprintf(&b, "**Session:** `%s`  \n", run.SessionID)
	}
	if run.CreatedAt != "" {
		fmt.Fprintf(&b, "**Created:** %s  \n", run.CreatedAt)
	}
	if len(run.Errors) > 0 {
		b.WriteString("\n## Errors\n\n")
		for _, e := range run.Errors {
			fmt.Fprintf(&b, "- `%s`: %s\n", e.Backend, e.Err)
		}
	}

	// Group items by source.
	bySource := map[string][]mem.Item{}
	for _, it := range items {
		bySource[it.Source] = append(bySource[it.Source], it)
	}
	sources := make([]string, 0, len(bySource))
	for s := range bySource {
		sources = append(sources, s)
	}
	sort.Strings(sources)

	b.WriteString("\n## Findings\n\n")
	for _, src := range sources {
		b.WriteString("### ")
		b.WriteString(src)
		b.WriteString("\n\n")
		its := bySource[src]
		// Sort by confidence desc
		sort.Slice(its, func(i, j int) bool { return its[i].Confidence > its[j].Confidence })
		for _, it := range its {
			conf := fmt.Sprintf("%.2f", it.Confidence)
			fmt.Fprintf(&b, "- **[%s]** %s\n", conf, it.Title)
			if it.URL != "" {
				fmt.Fprintf(&b, "  %s\n", it.URL)
			}
			if it.Snippet != "" {
				fmt.Fprintf(&b, "  > %s\n", truncateForMarkdown(it.Snippet, 200))
			}
		}
	}

	b.WriteString("\n---\n")
	b.WriteString("_Generated by `dark_mem_export_run` from `dark-research-mcp`._\n")
	return b.String()
}

func truncateForMarkdown(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max] + "…"
}

// --- diff ---

type memDiffArgs struct {
	RunA int64 `json:"run_a" jsonschema:"First run id"`
	RunB int64 `json:"run_b" jsonschema:"Second run id"`
}

func memDiffTool() Tool {
	def := mcp.NewTool("dark_mem_diff",
		mcp.WithDescription("Diff two research runs by item title. Reports items that appeared only in run A, only in run B, and in both. Useful for tracking OSINT drift over time ('what changed about CVE-2024-3094 between this week and last?') or comparing two queries on the same target."),
		mcp.WithNumber("run_a", mcp.Required(), mcp.Description("First run id")),
		mcp.WithNumber("run_b", mcp.Required(), mcp.Description("Second run id")),
	)
	return Tool{
		Definition: def,
		Handler: func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			var args memDiffArgs
			if err := bindArgs(req, &args); err != nil {
				return nil, err
			}
			m := sharedMem()
			if m == nil {
				return nil, fmt.Errorf("mem store not configured")
			}
			a, err := m.ListResearchItems(ctx, args.RunA, "", 9999)
			if err != nil {
				return nil, err
			}
			b, err := m.ListResearchItems(ctx, args.RunB, "", 9999)
			if err != nil {
				return nil, err
			}
			onlyA, onlyB, shared := diffItemsByTitle(a, b)
			return jsonResult(map[string]any{
				"run_a_id":       args.RunA,
				"run_b_id":       args.RunB,
				"count_only_a":   len(onlyA),
				"count_only_b":   len(onlyB),
				"count_shared":   len(shared),
				"only_in_run_a":  onlyA,
				"only_in_run_b":  onlyB,
				"shared":         shared,
			}), nil
		},
	}
}

// diffItemsByTitle partitions items by title (case-insensitive). Returns
// (onlyInA, onlyInB, shared). Used by dark_mem_diff.
func diffItemsByTitle(a, b []mem.Item) (onlyA, onlyB, shared []mem.Item) {
	aMap := map[string]mem.Item{}
	for _, it := range a {
		aMap[strings.ToLower(strings.TrimSpace(it.Title))] = it
	}
	bMap := map[string]mem.Item{}
	for _, it := range b {
		bMap[strings.ToLower(strings.TrimSpace(it.Title))] = it
	}
	for k, it := range aMap {
		if _, ok := bMap[k]; ok {
			shared = append(shared, it)
		} else {
			onlyA = append(onlyA, it)
		}
	}
	for k, it := range bMap {
		if _, ok := aMap[k]; ok {
			continue // already in shared
		}
		onlyB = append(onlyB, it)
	}
	return
}

// Compile-time check that we use time + json (prevent unused-import drift).
var _ = time.RFC3339
var _ = json.Marshal